[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
# https://docs.pytest.org/en/stable/customize.html
addopts = '''
-ra
--tb=line
-W error
--doctest-modules
--strict-markers
'''
# -ra: show extra test summary [...] (a)ll except passed [...]
# --tb=style: traceback print mode (auto/long/short/line/native/no)
# -W: set which warnings to report, "error" turns matching warnings into exceptions

testpaths = [
    "tests",
]

norecursedirs = [
    ".git",
    ".github",
    ".pytest_cache",
    "__pycache__",
]

[tool.coverage.run]
# https://coverage.readthedocs.io/en/latest/config.html
branch = true

[tool.coverage.report]
show_missing = true

[tool.black]
# https://black.readthedocs.io/en/stable/pyproject_toml.html
line-length = 99
target-version = ['py38']
exclude = '''
(
  /(
      \.git
    | \.github
    | \.pytest_cache
    | env
    | venv
  )/
)
'''
